export interface Incentive {
  name: string
  amount: string
  description: string
}

export const INCENTIVES_BY_STATE: Record<string, Incentive[]> = {
  ny: [
    { name: "NY State Solar Tax Credit", amount: "25% (up to $5,000)", description: "State income tax credit for residential solar installations." },
    { name: "NYSERDA NY-Sun Rebate", amount: "Varies by region", description: "Cash rebate paid directly to the installer, lowering your upfront cost." },
    { name: "NYC Property Tax Abatement", amount: "30% over 4 years", description: "NYC homeowners get a property tax abatement equal to 30% of system cost." },
    { name: "Property Tax Exemption", amount: "100%", description: "Solar installations are exempt from added property tax assessment in NY." },
    { name: "Net Metering", amount: "Full retail credit", description: "Sell excess energy back to the grid at full retail rate." },
  ],
  pa: [
    { name: "PA SREC Market", amount: "$30-40 per MWh", description: "Sell Solar Renewable Energy Credits generated by your system." },
    { name: "Net Metering", amount: "Full retail credit", description: "PECO, PPL, Duquesne Light and other utilities offer full retail net metering." },
    { name: "Property Tax Exemption", amount: "100%", description: "Solar systems are exempt from added property tax in PA." },
  ],
  md: [
    { name: "MD Residential Solar Grant", amount: "$1,000 flat", description: "One-time state grant for new residential solar installations." },
    { name: "MD SREC Market", amount: "$50-65 per MWh", description: "Sell SRECs generated by your system on Maryland's open market." },
    { name: "Property Tax Exemption", amount: "100%", description: "Solar installations are exempt from property tax in MD." },
    { name: "Sales Tax Exemption", amount: "100%", description: "Solar equipment purchases are exempt from MD sales tax." },
    { name: "Montgomery County Property Tax Credit", amount: "Up to $5,000", description: "Montgomery County offers an additional local property tax credit." },
  ],
  nj: [
    { name: "NJ SuSI Program (Successor Solar Incentive)", amount: "Varies", description: "Earn TRECs (Transition Renewable Energy Certificates) for energy generated." },
    { name: "Property Tax Exemption", amount: "100%", description: "Added value from solar is exempt from NJ property tax." },
    { name: "Sales Tax Exemption", amount: "100%", description: "Solar equipment purchases are exempt from NJ sales tax." },
    { name: "Net Metering", amount: "Full retail credit", description: "PSE&G, JCP&L, and ACE offer full retail net metering." },
  ],
  ct: [
    { name: "Residential Solar Investment Program", amount: "Varies", description: "CT Green Bank incentive for residential solar." },
    { name: "Property Tax Exemption", amount: "100%", description: "Solar installations are exempt from CT property tax." },
    { name: "Sales Tax Exemption", amount: "100%", description: "Solar equipment is exempt from CT sales tax." },
    { name: "Net Metering", amount: "Full retail credit", description: "Eversource and UI offer full retail net metering." },
  ],
  ma: [
    { name: "MA State Tax Credit", amount: "15% (up to $1,000)", description: "MA state income tax credit for residential solar." },
    { name: "SMART Program", amount: "Varies", description: "Solar Massachusetts Renewable Target — long-term performance incentive." },
    { name: "Property Tax Exemption", amount: "20 years", description: "Added value from solar is exempt from property tax for 20 years." },
    { name: "Sales Tax Exemption", amount: "100%", description: "Solar equipment is exempt from MA sales tax." },
    { name: "Net Metering", amount: "Full retail credit", description: "Eversource and National Grid offer full retail net metering." },
  ],
  ca: [
    { name: "Property Tax Exclusion", amount: "100%", description: "Added value from solar is excluded from property tax assessment in CA." },
    { name: "NEM 3.0 Net Billing", amount: "Varies", description: "Sell excess solar back to the grid at avoided cost rates." },
    { name: "DAC-SASH (Income-Qualified)", amount: "Varies", description: "Disadvantaged Communities Single-Family Solar Homes program for qualifying households." },
  ],
}
